# Generated by Django 3.0.5 on 2020-04-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200426_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='время добавления',
            new_name='comment_data',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='текст комментария',
            new_name='comment_text',
        ),
    ]
