# Generated by Django 3.0.5 on 2020-05-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200426_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.TextField(),
        ),
    ]
