# Generated by Django 3.0.5 on 2020-06-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200515_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.TextField(),
        ),
    ]
