# Generated by Django 3.0.5 on 2020-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200622_0748'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_name', 'article_date'], name='articles_ar_article_db8d29_idx'),
        ),
    ]
