# Generated by Django 3.0.5 on 2020-04-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_name', models.CharField(max_length=50)),
                ('photographer_bio', models.TextField()),
                ('photographer_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_image', models.ImageField(upload_to='')),
                ('photo_name', models.CharField(max_length=100)),
                ('photo_date', models.DateField()),
                ('photo_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographers.Photographer')),
            ],
        ),
    ]
