# Generated by Django 3.0.5 on 2020-05-06 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_author',
            new_name='photo_album',
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='photographer_bio',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='photographer_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_date',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='photographer_photo',
        ),
        migrations.AddField(
            model_name='photographer',
            name='photographer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
