# Generated by Django 3.0.5 on 2020-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_auto_20200506_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_image',
            field=models.TextField(),
        ),
    ]
