# Generated by Django 3.0.5 on 2020-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0003_auto_20200507_1102'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photographer',
            index=models.Index(fields=['photographer'], name='photographe_photogr_8cd8ed_idx'),
        ),
    ]
